language: scala

scala:
  - 2.10.2

jdk:
  - oraclejdk7

env:
  - TERM=dumb

install:
  - gradle setupCIWorkspace

after_success:
  - sudo apt-get install tree
  - gradle cobertura
  - gradle --info coveralls
